<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\shared\ShmContract.cs" Link="ShmContract.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(SIMHUB)' != ''">
    <Reference Include="SimHub.Plugins">
      <HintPath>$(SIMHUB)\SimHub.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameReaderCommon">
      <HintPath>$(SIMHUB)\GameReaderCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="log4net">
      <HintPath>$(SIMHUB)\log4net.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
